### ISSUE TITLE
Error in Build Process

### ISSUE THREAD

**Issue by sinkarharshad** [aehs29/yocto-workshop#1]
![yocto_error_in_build](https://cloud.githubusercontent.com/assets/18270841/24831992/28c23bba-1ca6-11e7-89bd-b86ebe3b6cf6.png)

Can you help me to resolve this error. 
Thank you in advance.

**Comment by ahcbb6** [comment]
You should never invoke bitbake as root, when necessary the build system uses pseudo itself.
